INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('person_1_name', 'Nurullakhon Nazrullaev', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('person_1_position', 'Director', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('telephone_contact_numbers', 'Contact with us', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('our_email_address', 'Our email adress', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('our_address', 'Our address', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('fill_out_the_following_to_contact_us', 'Drop me an Email', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('enter_nam_for_contact', 'Your Full Name', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('enter_phone_for_contact', 'Your email address', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('enter_subject_for_contact', ' Your Phone Number', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('enter_message_for_contact', 'Message', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('sed_message_for_contact', 'SEND MESSAGE', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('first_complete_projects', 'ENGLISH FOR SCIENCE ACADEMIC WRITING TRAINING PROGRAM', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('first_complete_projects_description', ' Client      Ministry of Higher education, science and innovations of the Republic of Uzbekistan', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('first_complete_projects_title', 'Funding Source:	The World Bank MUNIS project ', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('first_complete_projects_first', 'The main goal of the Project is to strengthen the academic English proficiency of 1000 (one thousand) successfully selected scientists from Uzbekistan by implementing the following tasks:', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('first_complete_projects_second', '−Training and developing scientists’ academic writing skills in preparation of publications for prestigious scientific journals.', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('first_complete_projects_third', '−Capacity building among scientists seeking foreign sources of funding (grants) and guiding them in application processes for MUNIS projects.', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('fourth_complete_projects', 'Early Childhood Development', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('fourth_complete_projects_description', 'Client : Development  Ministry of Preschool Education of the Republic of Uzbekistan', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('fourth_complete_projects_title', 'Funding Source:	The World Bank ', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('fourth_complete_projects_first', 'Provide English / Uzbek / Russian translation and adaptation of the following material:', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('fourth_complete_projects_second', 'Pedagogical and instructional material, including manuals, guidelines, conceptual frameworks, and reports. ', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('fourth_complete_projects_third', 'MELQO assessment materials, including cognitive materials, questionnaires, surveys.', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('fourth_complete_projects_fourth', 'Communication and educational material, including books, articles, publications, brochures, leaflets, scripts and letters.', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('fourth_complete_projects_fife', 'Outreach and dissemination material such as information, documents, social media posts, and blogs.', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('the_word_next_to_the_video_is_main_index', 'EMPOWERING EDUCATION AND INNOVATION', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('the_word_next_to_the_video_is_main_index_detail', 'By bridging academia, government, and business, we foster collaboration that enhances education, research, and innovation. ', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('our_services', 'CORE VALUES', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('brush_courses_title', 'Accountability', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('brush_courses_description', 'We take responsibility for our actions and results.', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('on_computers', 'Excellence', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('on_computers_description', 'We are dedicated to providing top-tier training services.', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('communication_with_teachers_as_well', 'Integrity', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('communication_with_teachers_as_well_description', 'We maintain high ethical standards.', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('feedback', 'Partners', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('feedback_description', 'Our Partners', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('we_have_such_courses', 'INVITED MENTORS', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('second_complete_projects', 'TECHNOLOGY COMMERCIALIZATION AND STARTUP PROJECTS IMPLEMENTATION', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('second_complete_projects_description', 'Client  	Ministry of Higher education, science and innovations of the Republic of Uzbekistan', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('second_complete_projects_title', 'Funding Source:	The World Bank MUNIS project ', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('second_complete_projects_first', 'The main goal of the Project is to support young people interested in STI to strengthen their skills in the field of technology commercialization and startup projects implementation to contribute to the achievement of the goals of the Innovation Development Strategy for 2022-2026. At the same time, the project provides expanding the pipeline for upcoming subcomponents of MUNIS project: ', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('second_complete_projects_second', 'Research Commercialization Program (RCP), and Business Investments in R&D Program (BIRD) and strength the promotion of the MUNIS project in the regions.', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('third_complete_projects', 'Language Training Service for U.S. Embassy staff in Tashkent', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('third_complete_projects_description', 'GOALS OF FOREIGN LANGUAGE TRAINING', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('third_complete_projects_title', 'The goal of training is to provide the student with the skills and knowledge necessary to rapidly reach the desired level of performance as identified in the training modules or lessons identified below:', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('third_complete_projects_first', 'Oral recognition and response module Each student, at the completion of training, shall be able to perform at the required level of proficiency.', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('third_complete_projects_second', 'Reading comprehension module Each student, at the completion of training, shall be able to perform the required level of proficiency.', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('change_the_language', 'Change the language', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('home_page', 'Home page', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('projects', 'Projects', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('projects_first', 'English for Science', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('projects_second', 'Technology commercialization and startup projects implementation', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('projects_third', 'LANGUAGE TRAINING PROGRAM FOR U.S. EMBASSY STAFF', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('projects_fourth', 'EARLY CHILDHOOD DEVELOPMENT', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('our_team', 'Our team', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('contact_with_us', 'Contact with us', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('enter_what_you_are_looking_for', 'Enter what you are looking for...', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('search', 'Search', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('mobile_description', 'Always study and you can do it', '1');
INSERT INTO "main"."Resources" ("Key", "Value", "CultureId") VALUES ('project', 'Project', '1');
